---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks:  'Windows.yml'
  when: ansible_os_family == 'Windows'

- include_tasks:  'default.yml'
  when: ansible_os_family != 'Windows'


