---
- name: Show Proxy Status
  debug:
    msg: "Use Proxy: http://{{ proxy_host }}:{{ proxy_port }}"
  when: use_proxy | bool

- name: Remove winhttp proxy settings
  win_http_proxy:
    proxy: ''
    bypass: ''
  when: (not use_proxy) | bool

- name: Remove Proxy Config
  win_regedit:
    path: 'HKLM:\SOFTWARE\Amazon Web Services\AWS Agent Updater'
    name: UseProxy
    data: 1
    type: dword
    state: absent
  when: (not use_proxy) | bool
  notify:
    - restart windows awsagent

- name: Download AWS Inspector agent installer.
  win_get_url:
    url: "{{ aws_inspector_url }}"
    dest: "{{ aws_inspector_installer_dest }}"
    proxy_url: '{{ proxy_url | default(omit) }}'

- name: Install Package
  win_package:
    path: "{{ aws_inspector_installer_dest }}"
    creates_service: '{{ aws_inspector_service_name }}'
    arguments: "AUTOUPDATE={{ aws_inspector_auto_update | lower }} /install /quiet /norestart"

- name: Set winhttp proxy settings
  win_http_proxy:
    proxy: "{{ proxy_host }}:{{ proxy_port }}"
    bypass:
     - "169.254.169.254"
     - <local>
  when: use_proxy | bool

- name: Set Proxy Config
  win_regedit:
    path: 'HKLM:\SOFTWARE\Amazon Web Services\AWS Agent Updater'
    name: UseProxy
    data: 1
    type: dword
  when: use_proxy | bool
  notify:
    - restart windows awsagent