---
- name: restart awsagent
  service: name={{ aws_inspector_service_name }} state=restarted
  when: ansible_os_family != "Windows"

- name: restart windows awsagent
  win_service:
    name: "{{ aws_inspector_service_name }}"
    state: "restarted"
  when: ansible_os_family == "Windows"
